demikernel/inetstack

src/collections/hashttlcache/mod.rs
src/collections/hashttlcache/tests.rs

In these changes, I refactored the implementation of the `HashTtlCache` module, fixed existing tests and added new ones. Overall these are the biggest changes:
- Simplified the logic of `HashTtlCache`
- Added `HashTtlCache.cleanup()`
- Add comments to the code
- Add test units for testing all cases of insertions in the cache.

Refactoring `HashTtlCache` Implementation and Tests

---

src/collections/waker_page.rs
src/protocols/icmpv4/peer.rs
src/protocols/tcp/active_open.rs
src/protocols/tcp/passive_open.rs

In this Pull Request I fix build warnings for unneeded type casts.

Dropping Unneeded Type Casts

---

src/protocols/tcp/active_open.rs
src/protocols/tcp/established/state/receiver.rs
src/protocols/tcp/passive_open.rs
src/protocols/udp/peer.rs

In this Pull Request I fix build warnings for using map unit functions.

Don't Using Map Unit Function

---

src/protocols/tcp/active_open.rs
src/protocols/tcp/established/mod.rs
src/protocols/tcp/passive_open.rs
src/protocols/tcp/peer.rs
src/test_helpers.rs

In this Pull Request I fix build warnings for usage of clone instead of copying.

Don't Use Clone When Copying is Available

---

src/protocols/arp/peer.rs

ARP cache eviction is causing TCP to misbehave. In this commit I temporarily disable this feature.

Disabling ARP Cache Eviction

---

src/protocols/tcp/established/background/mod.rs
src/protocols/tcp/tests/mod.rs
src/test_helpers.rs

- Set ARP initial state.
- dead_socket_tx for now.

Workaround for `tcp_connect` Test

---

.github/workflows/build.yml
src/operations.rs
src/protocols/tcp/peer.rs
tests/tcp.rs

In the Pull Request I fix two bugs in our regressions:
- Close accepted connections
- Don't bind active sockets
Additionally, I have changed tests to be single thread to avoid side-effect failures.

[test] Fixing Regressions

---

README.md

Readme previously referenced `$WORKDIR/demikernel` instead of `$WORKDIR/catnip`.

[doc] Update Readme to reference catnip directory

---

tests/tcp.rs

Description
========
Posix tests fail oftentimes due to race condition on resources.
In this Pull Request I'm disabling these tests so that we don't get false negatives in our regressions.

Ignore POSIX Tests

---

src/protocols/tcp/established/state/receiver.rs

Description
========
In this Pull Request we fix the bad scheme for acknowledge messages in TCP.
Previously we were acknowledging when we shouldn't.

Bad Acknowledgement Scheme

---

src/protocols/tcp/established/background/retransmitter.rs

Description
========
In this Pull Request I fix the following issues:
- **[Don't panic on Empty Unacknowledged Queue](b892a957bc08b5f5c3567ccb435e93d51d54754b)**: we may have a situation where the acknowledged was received, but the retransmission co-routiner was already scheduled to be executed.
- **[Pin Future for Fast Retransmission](1b3b29f20b80fb5a89896bf3f731e978ab63ed47)**: if fast retransmission flag has not changed, we should tag the co-routine as pending (before we would scheduled it anyways).
In additional, I also introduce the following enhancements on existing code:
- **[Faster Retransmission Logic](f2cdbb2104c22f44e4e50875af5cf5d0479e1771)**: re-organized retransmission logic to make it faster.
- **[Improving Code Style](e5f716d57d04307a3f57c5e44a5db7cdd063aa48)**: improved …

Bad Fast Retransmission on TCP

---

.github/workflows/build.yml
.github/workflows/test.yml
src/protocols/tcp/established/background/acknowledger.rs
src/protocols/tcp/established/background/closer.rs
src/protocols/tcp/established/ctrlblk.rs
src/protocols/tcp/established/sender/congestion_ctrl/cubic.rs
src/protocols/tcp/established/sender/mod.rs
src/protocols/tcp/segment.rs
src/protocols/tcp/tests/established.rs
src/protocols/tcp/tests/mod.rs

The main thing this check-in does is add a "send_ack()" routine to ControlBlock that sends an ACK to our peer.  The send_ack routine takes no arguments, as all the TCP header field information is filled in from values in the ControlBlock state.  I also modified the acknowledger to use this routine to send its ACKs.
I fixed a bug in doing so, as the acknowledger was sending all of its ACKs with zero in the sequence number field.  send_ack will set this value appropriately (i.e. to SND.NXT).  Without this fix, most other TCPs (i.e. correctly behaving ones) would reject most of our ACK packets.  We still have a bug in our receive path where we don't check incoming packets correctly, which is why we accepted these bad ACKs as okay.
I looked into changing all of the closer closures to use this …

[`tcp`] Adding `send_ack()`

---

src/protocols/tcp/established/background/closer.rs
src/protocols/tcp/established/background/retransmitter.rs
src/protocols/tcp/established/background/sender.rs
src/protocols/tcp/established/ctrlblk.rs
src/protocols/tcp/established/mod.rs
src/protocols/tcp/established/sender/mod.rs
src/protocols/tcp/peer.rs
src/protocols/tcp/sequence_number.rs
src/protocols/tcp/tests/established.rs
src/protocols/tcp/tests/mod.rs
src/test_helpers/runtime.rs

The main part of this PR is around fixing the TCP incoming packet processing to make all of the proper checks in the proper order.  With these changes we will now check incoming segments to ensure that they fit within the window (and will properly trim parts that don't fit in the case of segments that partially overlap the window).  We will now act properly upon receiving a RST, SYN or FIN.  We'll also make the proper state changes upon receiving an ACK for our FIN.
There are also some send-side changes around when/how to send a FIN.  A user close() call now places a zero-length buffer onto the end of unsent queue as a "marker" for the FIN.  When normal processing gets around to sending that buffer, it will set the FIN bit in the header.  This will need to be cleaned up further, although …

[tcp] Fix Numerous Receive Processing Problems

---

src/protocols/tcp/established/background/retransmitter.rs
src/protocols/tcp/established/background/sender.rs
src/protocols/tcp/established/ctrlblk.rs
src/protocols/tcp/established/sender/congestion_ctrl/cubic.rs
src/protocols/tcp/established/sender/congestion_ctrl/mod.rs
src/protocols/tcp/established/sender/mod.rs
src/protocols/tcp/established/sender/rto.rs

This PR renames several send-side variables to have more meaningful names (and names that should also be more familiar to people who have read the RFCs).
Additionally, it adds explicit types to some more variable declarations.

[tcp] Sender Naming

---

.github/workflows/build.yml
.github/workflows/test.yml

Description
========
In this PR I drop workflow dispatch in GitHub actions, because branch filtering is no longer supported on this dispatching option.

[test] Drop Workflow Dispatch

---

src/lib.rs
src/protocols/ethernet2/protocol.rs
src/protocols/tcp/established/background/retransmitter.rs
src/protocols/tcp/established/ctrlblk.rs
src/protocols/tcp/established/sender/mod.rs
src/protocols/tcp/tests/established.rs
src/test_helpers/engine.rs

This PR primarily fixes two major issues: the processing of ACKs we receive, and the handling of data segments we receive out of order.  We now properly handle any ACKs, and not just ones that correspond to our initial packetization.  We also now properly store out-of-order data (including potential FIN) for reinsertion into the data stream when a retransmitted or delayed packet arrives to fill the "hole" in the sequence number space (this was a potential data corruption bug).
This PR also improves when we send ACKs to be RFC 1122 compliant, how/when we update our send window, and the names of some variables to be more understandable.
This check-in contains partial or complete fixes for the Issues #63, #101, #102, #103.
*** In testing for this PR, a pre-existing bug was discovered in the …

[tcp] Fixes for Processing of Received ACKs, Receiving Out-of-order Segments, Delayed ACKs, etc.

---

.github/workflows/test.yml
Cargo.toml
README.md
src/lib.rs
src/protocols/tcp/segment.rs
tests/common/libos.rs
tests/tcp.rs
tests/udp.rs

Description
========
In this PR I rename the repository and all concerned code/documentation to InetStack, a shorthand for "Internet Stack".
The main reason for this change is to avoid misleading interpretation to external contributors.

[build] Renaming to InetStack

---

src/lib.rs
src/protocols/tcp/peer.rs

Description
-------------
This PR fixes https://github.com/demikernel/inetstack/issues/160.
Here is a summary of changes:
- I introduced some traces to help debugging interactions with the scheduler
- I replaced `get()` lookup in the sockets table by `remove()` to fix the bug

[tcp] Remove Queue Descriptor When Closing a Connection

---

src/protocols/ipv4/datagram.rs
src/protocols/ipv4/tests.rs

Description
--------------
This PR fixes https://github.com/demikernel/inetstack/issues/117.
------------------------
- Dropped failure return when parsing packet with `DSCP` flags.
- Dropped failure return when parsing packet with `ECN` flags.
- Fixed unit tests in IPv4 accordingly.

[ipv4] Don't Fail When Parsing Optional Features

---

src/protocols/tcp/peer.rs
tests/tcp.rs

Description
-------------
This PR fixes https://github.com/demikernel/inetstack/issues/100.
This PR Fixes https://github.com/demikernel/inetstack/issues/165.
Digest
--------
- Introduced unit tests to cover both isues
- Fixed issue https://github.com/demikernel/inetstack/issues/100 by adding match statement to check if socket is already bound.
- Fixed issue https://github.com/demikernel/inetstack/issues/165 by adding a check that traverses the sockets table and find out if there is any socket using that given local address.
Further Considerations
--------------------------
- A better fix for https://github.com/demikernel/inetstack/issues/165 would be to add a hashmap that keeps track of local addresses that are bound. However,this would introduce an additional table in our code. I believe …

[tcp] Fixes Bugs in `bind()`

---

src/protocols/tcp/peer.rs
tests/tcp.rs

Description
-------------
This PR fixes https://github.com/demikernel/inetstack/issues/170.
------------------------
- Fixed `listen()` to return `EADDRINUSE` when there is a socket listening on the target address/port pair.
- Fixed `listen()` to return `EADDRINUSE` when socket is already listening.
- Fixed `listen()` to return `EDESTADDRREQ` when socket is not bound to a local address.
- Fixed `listen()` to return `EINVAL` when socket is connecting/connected.
- Added unit test to cover `EADDRINUSE` case for `listen()`.
- Added unit test to cover `EDESTADDRREQ` case for `listen()`.
- Fixed typos in regressions.
Further Considerations
--------------------------
- A unit test that exercises the `EADDRINUSE` return condition when there is a socket listening on the target …

[tcp] Several Bug Fixes for `listen()`

---

src/protocols/ip/ephemeral.rs
src/protocols/tcp/peer.rs
tests/common/mod.rs
tests/tcp.rs

Description
-------------
This PR fixes https://github.com/demikernel/inetstack/issues/168.
------------------------
- Added unit test for "binding socket to ephemeral ports".
- Removed constraint for "binding sockets to ephemeral ports" in `bind()`.
- Added allocation for ephemeral a specific port number.
- Added rollback allocation logic in case `bind()` fails.

[tcp] Enable Binding to Ephemeral Ports

---

src/lib.rs
src/protocols/tcp/operations.rs
src/protocols/tcp/peer.rs
src/test_helpers/engine.rs
tests/tcp.rs

Description
-------------
This PR fixes https://github.com/demikernel/inetstack/issues/174.
------------------------
- Changed signature of `connect()` to return `Result<>`, thus enabling failing instead of panicking.
- Dropped useless `ConnectionFutureState` enumeration, if the operation fails straightaway there is no need to spawn a future.
- Added missing checks in `connect()` for cases in which the socket is connecting / connected.
- Fixed port reassigning when connecting bound sockets.
- Added unit test for establishing a connection using a bound active socket.

[ip] Don't Reassign the Local Port When Connecting a Bound Socket

---

src/protocols/tcp/peer.rs
src/protocols/udp/peer.rs
tests/tcp.rs
tests/udp.rs

Description
-------------
This PR fixes https://github.com/demikernel/inetstack/issues/169.
-------------------------
- Fixed `bind()` in TCP to accept zero as a wildcard ephemeral port
- Added support for ephemeral ports in UDP
- Enabled `bind()` in UDP to accept zero as a wildcard ephemeral port
- Added unit test for setting up a passive socket in TCP using an ephemeral port
- Added unit tests for setting up a socket in UDP using an ephemeral

[ip] Accept Zero as a Wildcard Ephemeral Port in `bind()`

---

src/protocols/ipv4/datagram.rs
src/protocols/ipv4/tests.rs

This PR fixes Issues #162 and #183.
The stack was mistakenly identifying IPv4 datagrams with a non-zero Identification field, or a cleared DF (don't fragment) bit in the Flags field, as fragments.  And then rejecting them (since we don't support fragmentation yet).  Neither of these fields is a reliable indicator of a fragment.
This PR:
- Removes the two bogus checks that were rejecting otherwise valid datagrams.
- Adds a new check for correctly identifying and rejecting fragments.
- Adds a new check for identifying and rejecting datagrams with the Reserved bit set in the Flags field.
- Fixes the tests for the above situations to test for the actual correct behavior.

[ip] Fixed Misidentification of Fragments in IPv4 Header Parsing

---

Cargo.toml
src/futures/operation/mod.rs
src/lib.rs
src/protocols/arp/cache/mod.rs
src/protocols/arp/cache/tests.rs
src/protocols/arp/peer.rs
src/protocols/arp/tests.rs
src/protocols/icmpv4/peer.rs
src/protocols/icmpv4/tests.rs
src/protocols/peer.rs
src/protocols/tcp/active_open.rs
src/protocols/tcp/established/background/acknowledger.rs
src/protocols/tcp/established/background/mod.rs
src/protocols/tcp/established/background/retransmitter.rs
src/protocols/tcp/established/background/sender.rs
src/protocols/tcp/established/ctrlblk.rs
src/protocols/tcp/established/mod.rs
src/protocols/tcp/established/sender.rs
src/protocols/tcp/operations.rs
src/protocols/tcp/passive_open.rs
src/protocols/tcp/peer.rs
src/protocols/tcp/tests/setup.rs
src/protocols/udp/peer.rs
src/test_helpers/engine.rs
src/test_helpers/mod.rs
src/test_helpers/runtime.rs
tests/common/libos.rs
tests/common/runtime.rs

Description
-------------
This PR updates the `runtime` crate.
-------------------------
- Updated `runtime` crate, which dropped trait bounds on the `SchedulerRuntime`
- Dropped `SchedulerRuntime` use from `Inetstack`
- Added `scheduler` and `clock` members to `Inetstack`, `Peer`, `Icpmv4Peer` `UdpPeer`, `TcpPeer` and `ArpPeer`
Further Considerations
---------------------------
- The changes unveiled that we should fix the signature of all functions that spawn co-routines, to enable failling instead of panicking.
- The changes unveiled a redundant interface for `TimerRc`.
- Once we drop `RT: Runtime`, we shall encapsulate all runtime objects (ex: `rng_seed`, `scheduler`, `clock`) on a structure.

[contrib] Updating `runtime` and Dropping `SchedulerRuntime`

---

src/lib.rs
src/protocols/icmpv4/peer.rs
src/protocols/peer.rs
src/protocols/tcp/peer.rs
src/protocols/udp/peer.rs
src/test_helpers/engine.rs

This PR fixes Issue #191 
The following peers' constructors panic on errors: `UdpPeer`, `Icmpv4Peer`, `Peer`, and `TcpPeer`. Instead of panicking, those peers' constructors should return a `Result<T, Fail>`
This PR:
Removes the `panic!` from UdpPeer and Icmpv4Peer and instead returns an Err(Fail)
Wraps the returned peer in an Ok(<Peer>) for UdpPeer, Icmpv4Peer, and TcpPeer
Changes the signature of the constructors of UdpPeer, Icmpv4Peer, TcpPeer, and Peer to return Result<T, Fail> 
Fixed up usage of these constructors in tests and in lib.rs to propagate the error

[inetstack] Constructors should fail instead of panicking
