demikernel/inetstack

src/protocols/arp/cache/mod.rs, src/protocols/arp/cache/tests.rs
- Dropped deadcode
- Add comments
- Fix clippy warnings
- Added more unit tests
=> ARP Cache Refactor

Cargo.toml, src/engine.rs, src/libos.rs, src/scheduler.rs, tests/tcp_loop.rs, tests/udp_echo.rs, tests/udp_loop.rs
In this Pull Request I drop the Tracy Client crate, which we were not using at all.
=> Dropping Tracy Client

src/protocols/ipv4/datagram.rs, src/protocols/tcp/segment.rs
In this Pull Request I fix build warnings for redundant slicing.
=> Dropping Redundant Slicing

src/file_table.rs, src/protocols/tcp/peer.rs
In this Pull Request I fix build warnings for unneeded return statments.
=> Unneeded Return Statement

src/collections/async_map.rs, src/file_table.rs, src/scheduler.rs, src/sync/threadunsafe.rs
In this Pull Request I fix build warnings for missing implementation for default trait.
=> Missing Implementation for Default Trait

src/protocols/icmpv4/peer.rs, src/protocols/ipv4/peer.rs, src/protocols/udp/peer.rs
In this Pull Request I fix build warnings for bad structure initialization.
=> Bad Structure Initialization

src/collections/waker_page.rs, src/protocols/ip/port.rs, src/protocols/tcp/segment.rs, src/protocols/udp/peer.rs, src/runtime.rs, src/scheduler.rs
In this Pull Request I fix various build warnings.
=> Fixing Various Build Warnings

src/engine.rs, src/protocols/arp/cache/mod.rs, src/protocols/arp/cache/tests.rs, src/protocols/arp/mod.rs, src/protocols/arp/msg/mod.rs, src/protocols/arp/options.rs, src/protocols/arp/pdu/mod.rs, src/protocols/arp/peer.rs, src/protocols/arp/tests.rs, src/test_helpers.rs, tests/udp_echo.rs
In this Pull Request I introduce the following changes:
- Re-Enabled Cache Cleanup
- Fixed ARP Setup in Unit Tests
- Moved ARPCache Initialization
- Moved ArpOptions into ArpPeer
=> Improvements on ARP Layer

Cargo.toml, src/scheduler.rs
In this Pull Request I replaced the `gen-iter` for `bit-iter` crate.
=> Replacing `gen-iter` for `bit-iter`

Cargo.toml, src/logging.rs, src/runtime.rs, src/test_helpers.rs, tests/udp_echo.rs
In this Pull Request I updated all dependencies of our project. Note that I have changed the code to enable the following external crates to be updated:
- `log`
- `arrayvec`
- `rand`
=> Updating Dependencies

Cargo.toml, src/futures_utility.rs, src/lib.rs, src/logging.rs, src/protocols/arp/peer.rs, src/protocols/icmpv4/peer.rs, src/runtime.rs, src/test_helpers.rs, tests/udp_echo.rs
Add `UtilityMethods` trait for useful high-level methods we want for our futures.
=> `with_timeout()` for Futures

.gitignore, src/lib.rs, src/protocols/arp/options.rs, src/protocols/tcp/options.rs, src/test_helpers.rs
In this Pull Request I fix the last clippy warnings in the source tree and enabled denial mode.
=> Deny Warnings

src/collections/bytes.rs
=> Revert to manual implementation of Bytes and BytesMut

src/protocols/arp/cache/mod.rs, src/protocols/arp/cache/tests.rs, src/protocols/arp/msg/mod.rs, src/protocols/arp/pdu/mod.rs, src/protocols/arp/peer.rs
In this Pull Request I refactor the ARP module. Overall, I split our logic across different files, I introduced getters/setters as well as constructions, and I added some documentation.
=> [arp] Refactoring Module

src/engine.rs, src/protocols/ethernet2/frame.rs, src/protocols/icmpv4/datagram.rs, src/protocols/icmpv4/peer.rs, src/protocols/ipv4/peer.rs
In this Pull Request I introduce some refactoring in our ICMPv4 code. Overall I split the logic in more files, I added getters and setters and I improved documentation.
=> [icmpv4] Refactoring Module

.github/workflows/test.yml
Description
========
In this Pull Request I fix Fetch & Merge strategy for GitHub Actions.
=> Bad Fetching & Merge Strategy

Makefile, src/collections/bytes.rs, src/libos.rs, src/protocols/tcp/established/state/receiver.rs, src/test_helpers.rs, tests/common/libos.rs, tests/common/runtime.rs, tests/tcp.rs, tests/udp.rs
Description
========
This Pull Request fixes issue https://github.com/demikernel/catnip/issues/81.
=> [libos] Don't Panic on Zero-Length Buffers

src/protocols/tcp/active_open.rs
Description
========
Changing the code to be conformant to [RFC 793 Section 3.4](https://datatracker.ietf.org/doc/html/rfc793#section-3.4):
> In all states except SYN-SENT, all reset (RST) segments are validated
by checking their SEQ-fields.  A reset is valid if its sequence number
is in the window.  In the SYN-SENT state (a RST received in response
to an initial SYN), the RST is acceptable if the ACK field
acknowledges the SYN.
=> [tcp] Don't Reset too Early while Establishing Connection

src/lib.rs, tests/tcp.rs, tests/udp.rs
Description
========
In this PR, I fix issue https://github.com/demikernel/demikernel/issues/71 for our network stack.
Related Issues
==========
I created an issue to keep track of the `TODO` comment that I added:
- https://github.com/demikernel/demikernel/issues/76
=> [pdpix] wait() and wait_any() System Calls Should Return an Error

Makefile, src/lib.rs, src/protocols/tcp/operations.rs, src/protocols/tcp/peer.rs
Description
========
In this PR I fix issue https://github.com/demikernel/catnip/issues/134.
In addition, I introduce some additional comments and type annotations to the modules that I touched.
=> [tcp] Leaking Queue Descriptor in `accept()`

src/lib.rs
Description
========
This PR introduces a workaround for the issue side-issue described in https://github.com/demikernel/catnip/issues/149.
=> [tcp] Process Futures at Each Packet
